pcf_handler:
  # PCF connection details
  pcf_base_url: "http://192.168.70.139:8000/npcf-policyauthorization/v1"
  use_tls: false
  api_version: "v1"
  
  # Logging configuration
  logging:
    level: "info"
    console_output: true
    file_output: true
    file_path: "/app/logs/pcf_handler.log"
    
  # Communication configuration
  communication:
    server_address: "0.0.0.0"
    server_port: "50055"
    core_address: "phine.af-core"
    core_port: "50051"