x-free5gc-defaults: &free5gc-defaults
  restart: "no"
  environment: &free5gc-default-env
    TZ: ${TZ:-Europe/Paris}

x-free5gc-nf: &free5gc-nf
  <<: *free5gc-defaults
  expose:
    - "8000"
  environment:
    <<: *free5gc-default-env
    GIN_MODE: release

services:
  free5gc-upf:
    <<: *free5gc-defaults
    profiles: [free5gc]
    container_name: upf
    image: ${UPF_IMAGE:-phinetech/oai-upf:fix-measurement-ie-v2}
    expose:
      - 2152/udp
      - 8805/udp
      - 8080/tcp
    volumes:
      - ./conf/oai_upf_config.yaml:/openair-upf/etc/config.yaml
      - /sys/fs/bpf:/sys/fs/bpf
      - /sys/kernel/debug:/sys/kernel/debug:rw
    depends_on:
      - free5gc-nrf
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    cap_drop:
      - ALL
    privileged: true
    network_mode: host
    extra_hosts:
      - oai-ext-dn:192.168.72.135
      - oai-nrf:192.168.70.130

  db:
    <<: *free5gc-defaults
    profiles: [free5gc]
    container_name: mongodb
    image: ${MONGO_IMAGE:-mongo:4.4}
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - ./free5gc/dump:/data/dump
      - ./free5gc/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
    networks:
      public_net:
        ipv4_address: 192.168.70.131
        aliases:
          - db

  free5gc-nrf:
    <<: *free5gc-nf
    profiles: [free5gc]
    container_name: nrf
    image: ${FREE5GC_NRF_IMAGE:-free5gc/nrf:v4.1.0}
    command: ./nrf -c ./config/nrfcfg.yaml
    volumes:
      - ./free5gc/config/nrfcfg.yaml:/free5gc/config/nrfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      <<: *free5gc-default-env
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      public_net:
        ipv4_address: 192.168.70.130
        aliases:
          - nrf.free5gc.org
    depends_on:
      - db

  free5gc-amf:
    <<: *free5gc-nf
    profiles: [free5gc]
    container_name: amf
    image: ${FREE5GC_AMF_IMAGE:-free5gc/amf:v4.1.0}
    command: ./amf -c ./config/amfcfg.yaml
    volumes:
      - ./free5gc/config/amfcfg.yaml:/free5gc/config/amfcfg.yaml
      - ./cert:/free5gc/cert
    networks:
      public_net:
        ipv4_address: 192.168.70.132
        aliases:
          - amf.free5gc.org
          - amf
    depends_on:
      - free5gc-nrf

  free5gc-ausf:
    <<: *free5gc-nf
    profiles: [free5gc]
    container_name: ausf
    image: ${FREE5GC_AUSF_IMAGE:-free5gc/ausf:v4.1.0}
    command: ./ausf -c ./config/ausfcfg.yaml
    volumes:
      - ./free5gc/config/ausfcfg.yaml:/free5gc/config/ausfcfg.yaml
      - ./cert:/free5gc/cert
    networks:
      public_net:
        ipv4_address: 192.168.70.138
        aliases:
          - ausf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-nssf:
    <<: *free5gc-nf
    profiles: [free5gc]
    container_name: nssf
    image: ${FREE5GC_NSSF_IMAGE:-free5gc/nssf:v4.1.0}
    command: ./nssf -c ./config/nssfcfg.yaml
    volumes:
      - ./free5gc/config/nssfcfg.yaml:/free5gc/config/nssfcfg.yaml
      - ./cert:/free5gc/cert
    networks:
      public_net:
        ipv4_address: 192.168.70.146
        aliases:
          - nssf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-pcf:
    <<: *free5gc-nf
    profiles: [free5gc]
    container_name: pcf
    image: ${FREE5GC_PCF_IMAGE:-phinetech/free5gc-pcf:latest}
    command: ./pcf -c ./config/pcfcfg.yaml
    volumes:
      - ./free5gc/config/pcfcfg.yaml:/free5gc/config/pcfcfg.yaml
      - ./cert:/free5gc/cert
    networks:
      public_net:
        ipv4_address: 192.168.70.139
        aliases:
          - pcf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-smf:
    <<: *free5gc-nf
    profiles: [free5gc]
    container_name: smf
    image: ${FREE5GC_SMF_IMAGE:-free5gc/smf:v4.1.0}
    command: ./smf -c ./config/smfcfg.yaml -u ./config/uerouting.yaml
    volumes:
      - ./free5gc/config/smfcfg.yaml:/free5gc/config/smfcfg.yaml
      - ./free5gc/config/uerouting.yaml:/free5gc/config/uerouting.yaml
      - ./cert:/free5gc/cert
    networks:
      public_net:
        ipv4_address: 192.168.70.133
        aliases:
          - smf.free5gc.org
    depends_on:
      - free5gc-nrf
      - free5gc-upf

  free5gc-udm:
    <<: *free5gc-nf
    profiles: [free5gc]
    container_name: udm
    image: ${FREE5GC_UDM_IMAGE:-free5gc/udm:v4.1.0}
    command: ./udm -c ./config/udmcfg.yaml
    volumes:
      - ./free5gc/config/udmcfg.yaml:/free5gc/config/udmcfg.yaml
      - ./cert:/free5gc/cert
    networks:
      public_net:
        ipv4_address: 192.168.70.137
        aliases:
          - udm.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-udr:
    <<: *free5gc-nf
    profiles: [free5gc]
    container_name: udr
    image: ${FREE5GC_UDR_IMAGE:-free5gc/udr:v4.1.0}
    command: ./udr -c ./config/udrcfg.yaml
    volumes:
      - ./free5gc/config/udrcfg.yaml:/free5gc/config/udrcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      <<: *free5gc-default-env
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      public_net:
        ipv4_address: 192.168.70.136
        aliases:
          - udr.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-chf:
    <<: *free5gc-nf
    profiles: [free5gc]
    container_name: chf
    image: ${FREE5GC_CHF_IMAGE:-free5gc/chf:v4.1.0}
    command: ./chf -c ./config/chfcfg.yaml
    volumes:
      - ./free5gc/config/chfcfg.yaml:/free5gc/config/chfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      <<: *free5gc-default-env
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      public_net:
        ipv4_address: 192.168.70.150
        aliases:
          - chf.free5gc.org
    depends_on:
      - db
      - free5gc-nrf
      - free5gc-webui

  free5gc-tngf:
    <<: *free5gc-defaults
    profiles: [free5gc]
    container_name: tngf
    image: ${FREE5GC_TNGF_IMAGE:-free5gc/tngf:v4.1.0}
    command: ./tngf -c ./config/tngfcfg.yaml
    volumes:
      - ./free5gc/config/tngfcfg.yaml:/free5gc/config/tngfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      <<: *free5gc-default-env
      GIN_MODE: release
    cap_add:
      - NET_ADMIN
    network_mode: host
    depends_on:
      - free5gc-amf
      - free5gc-smf
      - free5gc-upf

  free5gc-nef:
    <<: *free5gc-nf
    profiles: [free5gc]
    container_name: nef
    image: ${FREE5GC_NEF_IMAGE:-free5gc/nef:v4.1.0}
    command: ./nef -c ./config/nefcfg.yaml
    volumes:
      - ./free5gc/config/nefcfg.yaml:/free5gc/config/nefcfg.yaml
      - ./cert:/free5gc/cert
    networks:
      public_net:
        ipv4_address: 192.168.70.151
        aliases:
          - nef.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-webui:
    <<: *free5gc-defaults
    profiles: [free5gc]
    container_name: webui
    image: ${FREE5GC_WEBUI_IMAGE:-free5gc/webui:v4.1.0}
    command: ./webui -c ./config/webuicfg.yaml
    expose:
      - "2121"
    volumes:
      - ./free5gc/config/webuicfg.yaml:/free5gc/config/webuicfg.yaml
    environment:
      <<: *free5gc-default-env
      GIN_MODE: release
    networks:
      public_net:
        ipv4_address: 192.168.70.152
        aliases:
          - webui
    ports:
      - "5000:5000"
      - "2122:2122"
      - "2121:2121"
    depends_on:
      - db
      - free5gc-nrf
