services:
    mysql:
        container_name: "mysql"
        image: mysql:8.0
        volumes:
            - ./database/oai_db2.sql:/docker-entrypoint-initdb.d/01_oai_db.sql
            - ./database/oai_db_policy_data.sql:/docker-entrypoint-initdb.d/02_oai_db_policy_data.sql
            - ./healthscripts/mysql-healthcheck2.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 30
        networks:
            public_net:
                ipv4_address: 192.168.70.131

    mongodb:
        container_name: mongodb
        image: mongo:4.4
        command: mongod --port 27017
        expose:
            - "27017"
        # volumes:
        # # - dbdata:/data/db
        # - ./free5gc/dump:/data/dump
        # - ./free5gc/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
        networks:
            public_net:
                ipv4_address: 192.168.70.144
                aliases:
                    - db

    oai-udr:
        container_name: "oai-udr"
        image: phinetech/oai-udr:fix-am-data-endpoint
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/basic_nrf_config_ebpf.yaml:/openair-udr/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - mysql
            - oai-nrf
        networks:
            public_net:
                ipv4_address: 192.168.70.136
    oai-udm:
        container_name: "oai-udm"
        image: oaisoftwarealliance/oai-udm:v2.2.0
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/basic_nrf_config_ebpf.yaml:/openair-udm/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-nrf
        networks:
            public_net:
                ipv4_address: 192.168.70.137
    oai-ausf:
        container_name: "oai-ausf"
        image: oaisoftwarealliance/oai-ausf:v2.2.0
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/basic_nrf_config_ebpf.yaml:/openair-ausf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-nrf
        networks:
            public_net:
                ipv4_address: 192.168.70.138
    oai-nrf:
        container_name: "oai-nrf"
        image: oaisoftwarealliance/oai-nrf:v2.2.0
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/basic_nrf_config_ebpf.yaml:/openair-nrf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        networks:
            public_net:
                ipv4_address: 192.168.70.130
    oai-amf:
        container_name: "oai-amf"
        image: phinetech/oai-amf:fix-pcf-int
        expose:
            - 80/tcp
            - 8080/tcp
            - 38412/sctp
        volumes:
            - ./conf/basic_nrf_config_ebpf.yaml:/openair-amf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-nrf
            - oai-pcf
        networks:
            public_net:
                ipv4_address: 192.168.70.132
    oai-smf:
        container_name: "oai-smf"
        # SMF starts failing on commit 0e66e168, (Merge branch 'snssai_w_wo_ox' into 'develop')
        image: phinetech/oai-smf:fix-missing-an-type-v1
        # image: phinetech/oai-smf:smpa-latest
        # image: oaisoftwarealliance/oai-smf:v2.2.0
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        volumes:
            - ./conf/basic_nrf_config_ebpf.yaml:/openair-smf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-nrf
        networks:
            public_net:
                ipv4_address: 192.168.70.133
        extra_hosts:
            - "oai-upf:192.168.70.129"
    oai-pcf:
        container_name: "oai-pcf"
        # image: free5gc/pcf:latest
        image: phinetech/free5gc-pcf:latest
        command: ./pcf -c ./config/pcfcfg.yaml
        expose:
            - "8000"
        volumes:
            - ./free5gc/config/pcfcfg-oai.yaml:/free5gc/config/pcfcfg.yaml
            # - ./cert:/free5gc/cert
        environment:
            - GIN_MODE=release
            - TZ=Europe/Paris
        networks:
            public_net:
                ipv4_address: 192.168.70.139
                aliases:
                    - pcf.free5gc.org
        depends_on:
            - oai-nrf

    oai-upf:
        container_name: "oai-upf"
        image: oaisoftwarealliance/oai-upf:v2.2.0
        expose:
            - 2152/udp
            - 8805/udp
            - 8080/tcp
        volumes:
            - ./conf/basic_nrf_config_ebpf.yaml:/openair-upf/etc/config.yaml
            - /sys/fs/bpf:/sys/fs/bpf
            - /sys/kernel/debug:/sys/kernel/debug:rw
        # command: /openair-upf/bin/oai_upf -c /openair-upf/etc/config.yaml -o
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-nrf
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        network_mode: host
        extra_hosts:
            - "oai-ext-dn:192.168.72.135"
            - "oai-nrf:192.168.70.130"

    oai-ext-dn:
        privileged: true
        init: true
        container_name: oai-ext-dn
        image: oaisoftwarealliance/trf-gen-cn5g:latest
        environment:
            - EBPF_GW_SETUP=yes
            - EBPF_GW_N6_IP_ADDR=192.168.72.135
            - GW_SGI_IP_ADDR=192.168.70.135
            - GW_N3_IP_ADDR=192.168.71.135
            - UE_IP_ADDRESS_POOL=12.1.1.0/24
            - N6_UPF_IP_ADDR=192.168.72.129
            - SGI_DEMO_OAI_ADDR=192.168.70.129
        healthcheck:
            test: /bin/bash -c "ip r | grep 12.1.1"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.70.135
            n3_net:
                ipv4_address: 192.168.71.135
            n6_net:
                ipv4_address: 192.168.72.135
    oai-af:
        container_name: "oai-af"
        image: ubuntu:22.04
        expose:
            - 80/tcp
            - 8080/tcp
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-pcf
        command:
        - /bin/bash
        - -c
        - |
            apt update -y && apt install curl -y
            tail -f /dev/null
        networks:
            public_net:
                ipv4_address: 192.168.70.143
    # Southbound Handlers
    pcf_handler:
        image: phinetech/pcf-handler:${TAG:-latest}
        container_name: af-pcf-handler
        depends_on:
            - oai-pcf
            - af_core
        build:
            context: ..
            dockerfile: southbound/pcf_handler/Dockerfile
        networks:
            public_net:
                ipv4_address: 192.168.70.140

    # AF Core
    af_core:
        image: phinetech/af-core:${TAG:-latest}
        container_name: af-core
        build:
            context: ..
            dockerfile: af_core/Dockerfile
        networks:
            public_net:
                ipv4_address: 192.168.70.141

    # Northbound Components
    api_component:
        image: phinetech/af-api:${TAG:-latest}
        container_name: af-north-api
        depends_on:
            - af_core
        build:
            context: ..
            dockerfile: northbound/api_component/Dockerfile
        networks:
            public_net:
                ipv4_address: 192.168.70.142

    # UE and RAN Simulator
    gnb:
        privileged: true
        init: true
        container_name: gnb
        image: phinetech/ueransim:v3.2.7
        command:
            - /bin/bash
            - -c
            - |
                sleep 15
                nr-gnb -c /home/config-gnb.yaml
        volumes:
            - ./ueransim/oai-cn5g-gnb.yaml:/home/config-gnb.yaml
            - ./ueransim/oai-cn5g-ue.yaml:/home/config-ue.yaml
        depends_on:
          - oai-amf
          - oai-smf
          - oai-upf
          - oai-udr
          - oai-ext-dn
        networks:
            public_net:
                ipv4_address: 192.168.70.180
            n3_net:
                ipv4_address: 192.168.71.180
    ue:
        privileged: true
        init: true
        container_name: ue
        image: phinetech/ueransim:v3.2.7
        # nr-ue -c /home/config-ue.yaml
        # ping -I uesimtun0 8.8.8.8
        command:
            - /bin/bash
            - -c
            - |
                sleep 60
                echo "Starting UE..."
                nr-ue -c /home/config-ue.yaml
                tail -f /dev/null
        volumes:
            - ./ueransim/oai-cn5g-gnb.yaml:/home/config-gnb.yaml
            - ./ueransim/oai-cn5g-ue.yaml:/home/config-ue.yaml
        depends_on:
          - gnb
        networks:
            public_net:
                ipv4_address: 192.168.70.181

networks:
    public_net:
        driver: bridge
        name: demo-oai-public-net
        ipam:
            config:
                - subnet: 192.168.70.128/26
        driver_opts:
            com.docker.network.bridge.name: "demo-oai"
    n3_net:
        driver: bridge
        name: demo-oai-n3-net
        ipam:
            config:
                - subnet: 192.168.71.128/26
        driver_opts:
            com.docker.network.bridge.name: "demo-n3"
    n6_net:
        driver: bridge
        name: demo-oai-n6-net
        ipam:
            config:
                - subnet: 192.168.72.128/26
        driver_opts:
            com.docker.network.bridge.name: "demo-n6"
