version: '3.9'

services:
  # Northbound Components
  # ros2_component:
  #   image: phinetech/ros2-component:${TAG:-latest}
  #   build:
  #     context: ./northbound/ros2_component
  #     dockerfile: Dockerfile

  # sfc_component:
  #   image: phinetech/sfc-component:${TAG:-latest}
  #   build:
  #     context: ./northbound/sfc_component
  #     dockerfile: Dockerfile

  api_component:
    image: phinetech/af-api:${TAG:-latest}
    container_name: af-north-api
    build:
      context: ..
      dockerfile: northbound/api_component/Dockerfile
    networks:
      af_net:
        ipv4_address: 192.168.70.142

  # AF Core
  af_core:
    image: phinetech/af-core:${TAG:-latest}
    build:
      context: ..
      dockerfile: af_core/Dockerfile
    networks:
      af_net:
        ipv4_address: 192.168.70.141

  # Southbound Handlers
  pcf_handler:
    image: phinetech/pcf-handler:${TAG:-latest}
    build:
      context: ..
      dockerfile: southbound/pcf_handler/Dockerfile
    networks:
      af_net:
        ipv4_address: 192.168.70.140

  # nef_handler:
  #   image: phinetech/nef-handler:${TAG:-latest}
  #   build:
  #     context: ./southbound/nef_handler
  #     dockerfile: Dockerfile

  # tsctsf_handler:
  #   image: phinetech/tsctsf-handler:${TAG:-latest}
  #   build:
  #     context: ./southbound/tsctsf_handler
  #     dockerfile: Dockerfile

  # bsf_handler:
  #   image: phinetech/bsf-handler:${TAG:-latest}
  #   build:
  #     context: ./southbound/bsf_handler
  #     dockerfile: Dockerfile

  # nwdaf_handler:
  #   image: phinetech/nwdaf-handler:${TAG:-latest}
  #   build:
  #     context: ./southbound/nwdaf_handler
  #     dockerfile: Dockerfile

  # smf_handler:
  #   image: phinetech/smf-handler:${TAG:-latest}
  #   build:
  #     context: ./southbound/smf_handler
  #     dockerfile: Dockerfile

  # pin_handler:
  #   image: phinetech/pin-handler:${TAG:-latest}
  #   build:
  #     context: ./southbound/pin_handler
  #     dockerfile: Dockerfile

  # naf_prose_handler:
  #   image: phinetech/naf-prose-handler:${TAG:-latest}
  #   build:
  #     context: ./southbound/naf_prose_handler
  #     dockerfile: Dockerfile

  # Data Management
  # data_service:
  #   image: phinetech/data-service:${TAG:-latest}
  #   build:
  #     context: ./data_management
  #     dockerfile: Dockerfile

  # database_service:
  #   image: phinetech/database-service:${TAG:-latest}
  #   build:
  #     context: ./data_management/database # Assumes Dockerfile is in data_management/database/
  #     dockerfile: Dockerfile

networks:
  af_net:
    driver: bridge
    name: phine-af-net
    ipam:
      config:
        - subnet: "192.168.70.128/26"
    driver_opts:
      com.docker.network.bridge.name: phine-af-net
