pcf_handler:
  pcf:
    base_url: "http://192.168.70.139:8080/npcf-policyauthorization/v1"
    use_tls: false
    api_version: "v1"

  # Logging configuration
  logging:
    level: "info"
    console_output: true
    file_output: true
    file_path: "/app/logs/pcf_handler.log"

  # Communication configuration
  communication:
    kind: "grpc"
    listen:
      host: "0.0.0.0"
      port: 50055
    remote:
      host: "af-core"
      port: 50051